"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-06 12:15:39.750444

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "person",
        sa.Column("sub", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("roles", postgresql.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column("token_issued_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sub"),
    )
    op.create_table(
        "reference_item",
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "name", name="uq_reference_item_kind_name"),
    )
    op.create_index(op.f("ix_reference_item_kind"), "reference_item", ["kind"], unique=False)
    op.create_table(
        "expense_request",
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("moderator_id", sa.Integer(), nullable=False),
        sa.Column("payer_id", sa.Integer(), nullable=True),
        sa.Column("operation_type_id", sa.Integer(), nullable=False),
        sa.Column("payment_form_id", sa.Integer(), nullable=True),
        sa.Column("priority_id", sa.Integer(), nullable=False),
        sa.Column("situation", sa.Text(), nullable=False),
        sa.Column("solution", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("payment_period", sa.String(length=255), nullable=False),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("paid_on", sa.Date(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["person.id"],
        ),
        sa.ForeignKeyConstraint(
            ["moderator_id"],
            ["person.id"],
        ),
        sa.ForeignKeyConstraint(
            ["operation_type_id"],
            ["reference_item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payer_id"],
            ["person.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_form_id"],
            ["reference_item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["priority_id"],
            ["reference_item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_expense_request_author_id"), "expense_request", ["author_id"], unique=False)
    op.create_index(op.f("ix_expense_request_moderator_id"), "expense_request", ["moderator_id"], unique=False)
    op.create_index(op.f("ix_expense_request_status"), "expense_request", ["status"], unique=False)
    op.create_table(
        "attachment",
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("uploaded_by_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["expense_request.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["person.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(op.f("ix_attachment_request_id"), "attachment", ["request_id"], unique=False)
    op.create_table(
        "journal_entry",
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("status_changed", sa.Boolean(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["expense_request.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_journal_entry_request_id"), "journal_entry", ["request_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_journal_entry_request_id"), table_name="journal_entry")
    op.drop_table("journal_entry")
    op.drop_index(op.f("ix_attachment_request_id"), table_name="attachment")
    op.drop_table("attachment")
    op.drop_index(op.f("ix_expense_request_status"), table_name="expense_request")
    op.drop_index(op.f("ix_expense_request_moderator_id"), table_name="expense_request")
    op.drop_index(op.f("ix_expense_request_author_id"), table_name="expense_request")
    op.drop_table("expense_request")
    op.drop_index(op.f("ix_reference_item_kind"), table_name="reference_item")
    op.drop_table("reference_item")
    op.drop_table("person")
    # ### end Alembic commands ###
